Update base image to latest LTS
thyrlian/AndroidSDK pull request #64
Opened 2022-05-03 11:21 UTC by TimoPtr

2022-05-08 17:09 UTC, thyrlian commented
Thanks @TimoPtr for working on this PR, good initiative of upgrading the base image to the lastest LTS version.

The current Ubuntu version in use is 20.04.3 LTS, its end of standard support is April 2025 (according to Ubuntu's [releases page](https://wiki.ubuntu.com/Releases)).  The new one you proposed is 22.04 LTS, its end of standard support is April 2027.  In most cases, it's better to go with the latest LTS version.

I'll try my best to take some time reviewing your PR.  The catch is, the "smoke test" triggered by GitHub Actions only checks if all tools/commands are installed and can be found properly.  One concern is exactly as you mentioned - whether if the Android emulator can be launched flawlessly, due to the removal of the QT library.  I'll check it on my side, but please help check it as well on your side too, thank you.

2022-05-16 13:16 UTC, thyrlian requested changes
Thank you @TimoPtr, I really appreciate your great work of upgrading the base image and keeping corresponding dependencies up-to-date.

I'm so excited that finally, we've proved that the emulator is working perfectly even without the system-level installation of the `qt` package.

I've tagged two places with #CHANGE_REQUIRED, please fix those two minor things, and then we are more than happy to merge the PR.  Thanks.

2022-05-16 13:16 UTC, thyrlian commented on android-sdk/Dockerfile
> +    apt-get install -y --no-install-recommends git wget curl unzip zip && \
#CHANGE_REQUIRED

2022-05-16 13:31 UTC, TimoPtr commented on android-sdk/Dockerfile
> -    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends qt5-default
Thanks for your investigation 💪

2022-05-16 13:33 UTC, TimoPtr commented
@thyrlian I've applied the change thanks for your review 👍

2022-05-16 14:58 UTC, thyrlian commented
Great!  LGTM.  Thank you very much @TimoPtr.  I'll merge it once the CI workflow finishes.

2022-05-16 17:47 UTC, thyrlian approved these changes

2022-05-16 17:47 UTC, merged

2022-05-16 19:02 UTC, thyrlian commented
Just published a new version [8.0](https://hub.docker.com/layers/android-sdk/thyrlian/android-sdk/8.0/images/sha256-a9c645fe6922a4b775d27e3738d544fab5526fcb3fc944fe58196aa645e755cb), thanks again @TimoPtr for your great work!